// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvublmlanliawuuxioiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2dWJsbWxhbmxpYXd1dXhpb2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzU5NjIsImV4cCI6MjA2OTM1MTk2Mn0.TrkwqTZ2_MvS6ZXUNNVx_hhw648d5odQgtJoEq7MRf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});